
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/shop_shoe_superteam?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfnNotExist=true}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
#    url: jdbc:mysql://206.189.42.99/shop_shoe_superteam?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#    username: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
    signerKey: "1cLc5GX0Em888Eol5qUD7MmqprRtdyV7mFEBWftpuHDlmdbSZdXrTa74uv5q9/rD"
    validDuration: 3600
    refreshableDuration: 36000


vnPay:
  version: ${VNP_VERSION:2.1.0}
  command: ${VNP_COMMAND:pay}
  orderType: ${VNP_ORDER_TYPE:other}
  currCode: ${VNP_CURR_CODE:VND}
  hash-secret: ${VNP_HASH_SECRET:ANAIDKYHLTU5HVKRMUM4NVRMLCN0SJU1}
  tmn-code: ${VNP_TMN_CODE:8VWZT7KJ}
  payment-url: ${VNP_PAYMENT_URL:https://pay.vnpay.vn/vpcpay.html}
  return-url: ${VNP_RETURN_URL:http://localhost:8080/api/v1/payment/payment-callback}

mail:
  apiKey: ""

ai:
  openai:
    endpoint: ${AI_OPENAI_ENDPOINT:https://api.openai.com/v1/chat/completions}
    api-key: ${AI_OPENAI_APIKEY}


